// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record Betlist : ValueEnum<string>
{
    internal Betlist(string value)
        : base(value) { }

    public Betlist()
        : base("SETTLED") { }

    public static Betlist Settled = new("SETTLED");
    public static Betlist Running = new("RUNNING");
    public static Betlist All = new("ALL");
}
