// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record BetStatuses : ValueEnum<string>
{
    internal BetStatuses(string value)
        : base(value) { }

    public BetStatuses()
        : base("WON") { }

    public static BetStatuses Won = new("WON");
    public static BetStatuses Lose = new("LOSE");
    public static BetStatuses Cancelled = new("CANCELLED");
    public static BetStatuses Refunded = new("REFUNDED");
    public static BetStatuses NotAccepted = new("NOT_ACCEPTED");
    public static BetStatuses Accepted = new("ACCEPTED");
    public static BetStatuses PendingAcceptance = new("PENDING_ACCEPTANCE");
}
