// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record BetsGetBetsByTypeV4BetType : ValueEnum<string>
{
    internal BetsGetBetsByTypeV4BetType(string value)
        : base(value) { }

    public BetsGetBetsByTypeV4BetType()
        : base("SPREAD") { }

    public static BetsGetBetsByTypeV4BetType Spread = new("SPREAD");
    public static BetsGetBetsByTypeV4BetType Moneyline = new("MONEYLINE");
    public static BetsGetBetsByTypeV4BetType TotalPoints = new("TOTAL_POINTS");
    public static BetsGetBetsByTypeV4BetType TeamTotalPoints = new("TEAM_TOTAL_POINTS");
    public static BetsGetBetsByTypeV4BetType Special = new("SPECIAL");
    public static BetsGetBetsByTypeV4BetType Parlay = new("PARLAY");
    public static BetsGetBetsByTypeV4BetType Teaser = new("TEASER");
    public static BetsGetBetsByTypeV4BetType Manual = new("MANUAL");
}
