// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PinnacleBets.Models;

/// <summary>
/// Possible keys \:
/// * correctTeam1Id
/// * correctTeam2Id
/// * correctListedPitcher1
/// * correctListedPitcher2
/// * correctSpread
/// * correctTotalPoints
/// * correctTeam1TotalPoints
/// * correctTeam2TotalPoints
/// * correctTeam1Score
/// * correctTeam2Score
/// * correctTeam1TennisSetsScore
/// * correctTeam2TennisSetsScore
/// </summary>
public record CancellationReason(
    [property: JsonPropertyName("code")] string Code,
    [property:
        JsonPropertyName("details"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<CancellationDetailsItem>? Details = null
);
