// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PinnacleBets.Models;

public record CancellationDetailsItem(
    [property: JsonPropertyName("key"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Key = null,
    [property:
        JsonPropertyName("value"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Value = null
);
