// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PinnacleBets.Models;

public record GetBetsByTypeResponseV4(
    /// <value>Whether there are more pages available.</value>
    [property:
        JsonPropertyName("moreAvailable"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? MoreAvailable = null,
    /// <value>Page size. Default is 1000.</value>
    [property:
        JsonPropertyName("pageSize"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? PageSize = null,
    /// <value>Starting record number of the result set. Records start at zero</value>
    [property:
        JsonPropertyName("fromRecord"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? FromRecord = null,
    /// <value>Ending record number of the result set.</value>
    [property:
        JsonPropertyName("toRecord"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? ToRecord = null,
    /// <value>A collection of placed straight bets.</value>
    [property:
        JsonPropertyName("straightBets"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<StraightBetV4>? StraightBets = null,
    /// <value>A collection of placed parlay bets.</value>
    [property:
        JsonPropertyName("parlayBets"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ParlayBet>? ParlayBets = null,
    /// <value>A collection of placed teaser bets.</value>
    [property:
        JsonPropertyName("teaserBets"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<TeaserBet>? TeaserBets = null,
    /// <value>A collection of placed special bets.</value>
    [property:
        JsonPropertyName("specialBets"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<SpecialBet>? SpecialBets = null,
    /// <value>A collection of placed manual bets.</value>
    [property:
        JsonPropertyName("manualBets"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ManualBet>? ManualBets = null
);
