// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PinnacleBets.Models;

public record MultiBetResponseSpecialBetResponse(
    /// <value>The individual bets.</value>
    [property:
        JsonPropertyName("bets"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<SpecialBetResponse>? Bets = null
);
