// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

/// <summary>
/// Bet odds format.
/// AMERICAN = American odds format,
/// DECIMAL = Decimal (European) odds format,
/// HONGKONG = Hong Kong odds format,
/// INDONESIAN = Indonesian odds format,
/// MALAY = Malaysian odds format
/// </summary>
public record OddsFormat : ValueEnum<string>
{
    internal OddsFormat(string value)
        : base(value) { }

    public OddsFormat()
        : base("AMERICAN") { }

    public static OddsFormat American = new("AMERICAN");
    public static OddsFormat Decimal_ = new("DECIMAL");
    public static OddsFormat Hongkong = new("HONGKONG");
    public static OddsFormat Indonesian = new("INDONESIAN");
    public static OddsFormat Malay = new("MALAY");
}
