// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record ParlayLegResponse(
    /// <value>Status of the request.</value>
    [property:
        JsonPropertyName("status"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ParlayLegResponse.ParlayLegResponseStatus? Status = null,
    /// <value>
    /// When Status is PROCESSED_WITH_ERROR, provides a code indicating the specific problem.
    ///
    /// CANNOT_PARLAY_LIVE_GAME = The wager is placed on Live game,
    /// CORRELATED = The leg is correlated with another one,
    /// EVENT_NO_LONGER_AVAILABLE_FOR_BETTING = The event is no longer offered,
    /// EVENT_NOT_OFFERED_FOR_PARLAY = The event is not offered for parlaying,
    /// INVALID_EVENT = Live betting is not allowed at this moment,
    /// INVALID_LEG_BET_TYPE = Leg bet type is not accepted for parlaying. Accepted values are SPREAD, MONEYLINE, TOTAL_POINTS,
    /// INVALID_PARLAY_BET = The leg did not validated due to error on Parlay Bet. Check the error PlaceParlayBet response for error details,
    /// LINE_CHANGED = Bet is submitted on a line that has changed,
    /// LINE_DOES_NOT_BELONG_TO_EVENT = LineId does not match the EventId specified in the request,
    /// LISTED_PITCHERS_SELECTION_ERROR = If bet was submitted with pitcher1MustStart and/or pitcher2MustStart parameters with values that are not allowed,
    /// ODDS_NO_LONGER_OFFERED_FOR_PARLAY_1 = Due to line change odds are not offered for parlaying,
    /// ODDS_NO_LONGER_OFFERED_FOR_PARLAY_2 = Due to line change odds are not offered for parlaying,
    /// ODDS_NO_LONGER_OFFERED_FOR_PARLAY_3 = Due to line change odds are not offered for parlaying,
    /// OFFLINE_EVENT = Bet is submitted on an event that is offline or with incorrect lineId,
    /// PAST_CUTOFFTIME = Bet is submitted on a game after the betting cutoff time,
    /// SYSTEM_ERROR_1 = Unexpected error,
    /// SYSTEM_ERROR_2 = Unexpected error,
    /// SYSTEM_ERROR_3 = Unexpected error,
    /// LINE_IS_NOT_AVAILABLE = Line is not available for the specified Parlay Leg,
    /// PERIOD_IS_DISALLOWED_FOR_SAME_GAME_PARLAY = Period is not allowed to be parlayed on a same event,
    /// BETTING_SUSPENDED - Due to anomalous market circumstances bets are not currently being accepted on this line. Try again with next LineId.
    /// </value>
    [property: JsonPropertyName("errorCode")]
        ParlayLegResponse.ParlayLegResponseErrorCode? ErrorCode = null,
    /// <value>Echo of the legId from the request.</value>
    [property:
        JsonPropertyName("legId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? LegId = null,
    /// <value>Line identification that bet was placed on.</value>
    [property:
        JsonPropertyName("lineId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? LineId = null,
    /// <value>If bet was accepted on alternate line, the altLineId will be returned.</value>
    [property: JsonPropertyName("altLineId")]
        long? AltLineId = null,
    /// <value>Price that the bet was placed on.</value>
    [property:
        JsonPropertyName("price"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Price = null,
    /// <value>If errorCode is CORRELATED will contain legIds of all correlated legs.</value>
    [property:
        JsonPropertyName("correlatedLegs"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<string>? CorrelatedLegs = null
)
{
    /// <summary>Status of the request.</summary>
    public record ParlayLegResponseStatus : ValueEnum<string>
    {
        internal ParlayLegResponseStatus(string value)
            : base(value) { }

        public ParlayLegResponseStatus()
            : base("PROCESSED_WITH_ERROR") { }

        public static ParlayLegResponseStatus ProcessedWithError = new("PROCESSED_WITH_ERROR");
        public static ParlayLegResponseStatus Valid = new("VALID");
    }

    /// <summary>
    /// When Status is PROCESSED_WITH_ERROR, provides a code indicating the specific problem.
    ///
    /// CANNOT_PARLAY_LIVE_GAME = The wager is placed on Live game,
    /// CORRELATED = The leg is correlated with another one,
    /// EVENT_NO_LONGER_AVAILABLE_FOR_BETTING = The event is no longer offered,
    /// EVENT_NOT_OFFERED_FOR_PARLAY = The event is not offered for parlaying,
    /// INVALID_EVENT = Live betting is not allowed at this moment,
    /// INVALID_LEG_BET_TYPE = Leg bet type is not accepted for parlaying. Accepted values are SPREAD, MONEYLINE, TOTAL_POINTS,
    /// INVALID_PARLAY_BET = The leg did not validated due to error on Parlay Bet. Check the error PlaceParlayBet response for error details,
    /// LINE_CHANGED = Bet is submitted on a line that has changed,
    /// LINE_DOES_NOT_BELONG_TO_EVENT = LineId does not match the EventId specified in the request,
    /// LISTED_PITCHERS_SELECTION_ERROR = If bet was submitted with pitcher1MustStart and/or pitcher2MustStart parameters with values that are not allowed,
    /// ODDS_NO_LONGER_OFFERED_FOR_PARLAY_1 = Due to line change odds are not offered for parlaying,
    /// ODDS_NO_LONGER_OFFERED_FOR_PARLAY_2 = Due to line change odds are not offered for parlaying,
    /// ODDS_NO_LONGER_OFFERED_FOR_PARLAY_3 = Due to line change odds are not offered for parlaying,
    /// OFFLINE_EVENT = Bet is submitted on an event that is offline or with incorrect lineId,
    /// PAST_CUTOFFTIME = Bet is submitted on a game after the betting cutoff time,
    /// SYSTEM_ERROR_1 = Unexpected error,
    /// SYSTEM_ERROR_2 = Unexpected error,
    /// SYSTEM_ERROR_3 = Unexpected error,
    /// LINE_IS_NOT_AVAILABLE = Line is not available for the specified Parlay Leg,
    /// PERIOD_IS_DISALLOWED_FOR_SAME_GAME_PARLAY = Period is not allowed to be parlayed on a same event,
    /// BETTING_SUSPENDED - Due to anomalous market circumstances bets are not currently being accepted on this line. Try again with next LineId.
    /// </summary>
    public record ParlayLegResponseErrorCode : ValueEnum<string>
    {
        internal ParlayLegResponseErrorCode(string value)
            : base(value) { }

        public ParlayLegResponseErrorCode()
            : base("CANNOT_PARLAY_LIVE_GAME") { }

        public static ParlayLegResponseErrorCode CannotParlayLiveGame =
            new("CANNOT_PARLAY_LIVE_GAME");
        public static ParlayLegResponseErrorCode Correlated = new("CORRELATED");
        public static ParlayLegResponseErrorCode EventNoLongerAvailableForBetting =
            new("EVENT_NO_LONGER_AVAILABLE_FOR_BETTING");
        public static ParlayLegResponseErrorCode EventNotOfferedForParlay =
            new("EVENT_NOT_OFFERED_FOR_PARLAY");
        public static ParlayLegResponseErrorCode InvalidEvent = new("INVALID_EVENT");
        public static ParlayLegResponseErrorCode InvalidLegBetType = new("INVALID_LEG_BET_TYPE");
        public static ParlayLegResponseErrorCode InvalidParlayBet = new("INVALID_PARLAY_BET");
        public static ParlayLegResponseErrorCode LineChanged = new("LINE_CHANGED");
        public static ParlayLegResponseErrorCode LineDoesNotBelongToEvent =
            new("LINE_DOES_NOT_BELONG_TO_EVENT");
        public static ParlayLegResponseErrorCode OddsNoLongerOfferedForParlay1 =
            new("ODDS_NO_LONGER_OFFERED_FOR_PARLAY_1");
        public static ParlayLegResponseErrorCode OddsNoLongerOfferedForParlay2 =
            new("ODDS_NO_LONGER_OFFERED_FOR_PARLAY_2");
        public static ParlayLegResponseErrorCode OddsNoLongerOfferedForParlay3 =
            new("ODDS_NO_LONGER_OFFERED_FOR_PARLAY_3");
        public static ParlayLegResponseErrorCode OfflineEvent = new("OFFLINE_EVENT");
        public static ParlayLegResponseErrorCode PastCutofftime = new("PAST_CUTOFFTIME");
        public static ParlayLegResponseErrorCode SystemError1 = new("SYSTEM_ERROR_1");
        public static ParlayLegResponseErrorCode SystemError2 = new("SYSTEM_ERROR_2");
        public static ParlayLegResponseErrorCode SystemError3 = new("SYSTEM_ERROR_3");
        public static ParlayLegResponseErrorCode LineIsNotAvailable = new("LINE_IS_NOT_AVAILABLE");
        public static ParlayLegResponseErrorCode PeriodIsDisallowedForSameGameParlay =
            new("PERIOD_IS_DISALLOWED_FOR_SAME_GAME_PARLAY");
        public static ParlayLegResponseErrorCode BettingSuspended = new("BETTING_SUSPENDED");
    }
}
