// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record ParlayBet(
    /// <value>Bet identification</value>
    [property: JsonPropertyName("betId")]
        long BetId,
    /// <value>Wager identification. All bets placed thru the API will have value 1. Website Classic view supports multiple contest(special) bets placement in the same bet slip in that case the bet would have appropriate wager number, as well as all round robin parlay bets.</value>
    [property: JsonPropertyName("wagerNumber")]
        long WagerNumber,
    /// <value>
    /// Bet Status.
    ///
    /// ACCEPTED = Bet was accepted.
    /// CANCELLED = Bet is cancelled as per Pinnacle betting rules.
    /// LOST = The bet is settled as lose.
    /// PENDING_ACCEPTANCE = This status is reserved only for live bets. If a live bet is placed during danger zone or live delay is applied, it will be in PENDING_ACCEPTANCE , otherwise in ACCEPTED status. From this status bet can go to ACCEPTED or REJECTED status.
    /// REFUNDED = When an event is cancelled or when the bet is settled as push, the bet will have REFUNDED status.
    /// NOT_ACCEPTED = Bet was not accepted. Bet can be in this status only if it was previously in PENDING_ACCEPTANCE status.
    /// WON = The bet is settled as won.
    /// PARTIAL_WON  - If gross payout is greater than the  stake. Only for parlays with the asian handicap legs.
    /// PARTIAL_LOST  - If gross payout is less or equal to the stake. Only for parlays with the asian handicap legs.
    /// </value>
    [property: JsonPropertyName("betStatus")]
        ParlayBet.ParlayBetBetStatus BetStatus,
    [property: JsonPropertyName("betType")] string BetType,
    /// <value>Win amount.</value>
    [property: JsonPropertyName("win")]
        double Win,
    /// <value>Risk amount.</value>
    [property: JsonPropertyName("risk")]
        double Risk,
    /// <value>
    /// Bet odds format.
    /// AMERICAN = American odds format,
    /// DECIMAL = Decimal (European) odds format,
    /// HONGKONG = Hong Kong odds format,
    /// INDONESIAN = Indonesian odds format,
    /// MALAY = Malaysian odds format
    /// </value>
    [property: JsonPropertyName("oddsFormat")]
        OddsFormat OddsFormat,
    /// <value>Update Sequence</value>
    [property: JsonPropertyName("updateSequence")]
        long UpdateSequence,
    [property: JsonPropertyName("legs")] List<ParlayLeg> Legs,
    /// <value>Unique Request Id</value>
    [property:
        JsonPropertyName("uniqueRequestId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? UniqueRequestId = null,
    /// <value>Win-Loss for settled bets.</value>
    [property: JsonPropertyName("winLoss")]
        double? WinLoss = null,
    /// <value>Client’s commission on the bet.</value>
    [property: JsonPropertyName("customerCommission")]
        double? CustomerCommission = null,
    /// <value>
    /// Possible keys \:
    /// * correctTeam1Id
    /// * correctTeam2Id
    /// * correctListedPitcher1
    /// * correctListedPitcher2
    /// * correctSpread
    /// * correctTotalPoints
    /// * correctTeam1TotalPoints
    /// * correctTeam2TotalPoints
    /// * correctTeam1Score
    /// * correctTeam2Score
    /// * correctTeam1TennisSetsScore
    /// * correctTeam2TennisSetsScore
    /// </value>
    [property:
        JsonPropertyName("cancellationReason"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        CancellationReason? CancellationReason = null,
    [property:
        JsonPropertyName("price"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Price = null,
    /// <value>Only for settled parlay. Final price may differ in case leg was cancelled or half won</value>
    [property:
        JsonPropertyName("finalPrice"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? FinalPrice = null
)
{
    /// <summary>
    /// Bet Status.
    ///
    /// ACCEPTED = Bet was accepted.
    /// CANCELLED = Bet is cancelled as per Pinnacle betting rules.
    /// LOST = The bet is settled as lose.
    /// PENDING_ACCEPTANCE = This status is reserved only for live bets. If a live bet is placed during danger zone or live delay is applied, it will be in PENDING_ACCEPTANCE , otherwise in ACCEPTED status. From this status bet can go to ACCEPTED or REJECTED status.
    /// REFUNDED = When an event is cancelled or when the bet is settled as push, the bet will have REFUNDED status.
    /// NOT_ACCEPTED = Bet was not accepted. Bet can be in this status only if it was previously in PENDING_ACCEPTANCE status.
    /// WON = The bet is settled as won.
    /// PARTIAL_WON  - If gross payout is greater than the  stake. Only for parlays with the asian handicap legs.
    /// PARTIAL_LOST  - If gross payout is less or equal to the stake. Only for parlays with the asian handicap legs.
    /// </summary>
    public record ParlayBetBetStatus : ValueEnum<string>
    {
        internal ParlayBetBetStatus(string value)
            : base(value) { }

        public ParlayBetBetStatus()
            : base("ACCEPTED") { }

        public static ParlayBetBetStatus Accepted = new("ACCEPTED");
        public static ParlayBetBetStatus Cancelled = new("CANCELLED");
        public static ParlayBetBetStatus Lost = new("LOST");
        public static ParlayBetBetStatus PendingAcceptance = new("PENDING_ACCEPTANCE");
        public static ParlayBetBetStatus Refunded = new("REFUNDED");
        public static ParlayBetBetStatus NotAccepted = new("NOT_ACCEPTED");
        public static ParlayBetBetStatus Won = new("WON");
        public static ParlayBetBetStatus PartialWon = new("PARTIAL_WON");
        public static ParlayBetBetStatus PartialLost = new("PARTIAL_LOST");
    }
}
