// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PinnacleBets.Models;

public record PlaceTeaserBetRequest(
    /// <value>Client generated GUID for uniquely identifying the bet.</value>
    [property:
        JsonPropertyName("uniqueRequestId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? UniqueRequestId = null,
    /// <value>Unique identifier. Teaser details can be retrieved from a call to Get Teaser Groups endpoint.</value>
    [property:
        JsonPropertyName("teaserId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? TeaserId = null,
    /// <value>
    /// Bet odds format.
    /// AMERICAN = American odds format,
    /// DECIMAL = Decimal (European) odds format,
    /// HONGKONG = Hong Kong odds format,
    /// INDONESIAN = Indonesian odds format,
    /// MALAY = Malaysian odds format
    /// </value>
    [property:
        JsonPropertyName("oddsFormat"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        OddsFormat? OddsFormat = null,
    /// <value>Whether the stake amount is risk or win amount.</value>
    [property:
        JsonPropertyName("winRiskStake"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? WinRiskStake = null,
    /// <value>amount in client’s currency.</value>
    [property:
        JsonPropertyName("stake"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Stake = null,
    /// <value>Collection of legs.</value>
    [property:
        JsonPropertyName("legs"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<TeaserBetLeg>? Legs = null
);
