// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record RoundRobinOptionWithOdds(
    [property:
        JsonPropertyName("roundRobinOption"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        RoundRobinOptionWithOdds.RoundRobinOption? RoundRobinOption_ = null,
    /// <value>Parlay odds for this option.</value>
    [property:
        JsonPropertyName("odds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Odds = null,
    /// <value>Unrounded parlay odds in decimal format to be used for calculations only</value>
    [property:
        JsonPropertyName("unroundedDecimalOdds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? UnroundedDecimalOdds = null
)
{
    public record RoundRobinOption : ValueEnum<string>
    {
        internal RoundRobinOption(string value)
            : base(value) { }

        public RoundRobinOption()
            : base("Parlay") { }

        public static RoundRobinOption Parlay = new("Parlay");
        public static RoundRobinOption TwoLegRoundRobin = new("TwoLegRoundRobin");
        public static RoundRobinOption ThreeLegRoundRobin = new("ThreeLegRoundRobin");
        public static RoundRobinOption FourLegRoundRobin = new("FourLegRoundRobin");
        public static RoundRobinOption FiveLegRoundRobin = new("FiveLegRoundRobin");
        public static RoundRobinOption SixLegRoundRobin = new("SixLegRoundRobin");
        public static RoundRobinOption SevenLegRoundRobin = new("SevenLegRoundRobin");
        public static RoundRobinOption EightLegRoundRobin = new("EightLegRoundRobin");
    }
}
