// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record SortDir : ValueEnum<string>
{
    internal SortDir(string value)
        : base(value) { }

    public SortDir()
        : base("ASC") { }

    public static SortDir Asc = new("ASC");
    public static SortDir Desc = new("DESC");
}
