// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record SpecialBetResponse(
    /// <value>Status of the request.</value>
    [property:
        JsonPropertyName("status"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        SpecialBetResponse.SpecialBetResponseStatus? Status = null,
    /// <value>
    /// When Status is PROCESSED_WITH_ERROR, provides a code indicating the specific problem.
    ///
    /// ALL_BETTING_CLOSED = Betting is not allowed at this moment. This may happen during system maintenance.
    ///  ABOVE_MAX_BET_AMOUNT = Stake is above allowed maximum amount,
    ///  BELOW_MIN_BET_AMOUNT = Stake is below allowed minimum amount,
    ///  BLOCKED_BETTING = Betting is suspended for the client,
    ///  BLOCKED_CLIENT = Client is no longer active,
    ///  CONTEST_NOT_FOUND = Incorrect contest id provided or contest is no longer available,
    ///  DUPLICATED_REQUEST = UniqueRequestId must be unique for each bet,
    ///  INCOMPLETE_CUSTOMER_BETTING_PROFILE = Customer profile could not be loaded,
    ///  INSUFFICIENT_FUNDS = Bet is submitted by a client with insufficient funds,
    ///  INVALID_COUNTRY = Client country is not allowed for betting,
    ///  INVALID_REQUEST = Special bet request is not valid,
    ///  LINE_CHANGED = Bet is submitted on a line that has changed,
    ///  PAST_CUTOFFTIME = Bet is submitted on a game after the betting cutoff time,
    ///  RESPONSIBLE_BETTING_LOSS_LIMIT_EXCEEDED = Self-imposed loss limit exceeded,
    ///  RESPONSIBLE_BETTING_RISK_LIMIT_EXCEEDED = Self-imposed risk limit exceeded,
    ///  SYSTEM_ERROR_1 = Unexpected error,
    ///  SYSTEM_ERROR_2 = Unexpected error,
    ///  UNIQUE_REQUEST_ID_REQUIRED = UniqueRequestId is missing,
    ///  INVALID_CUSTOMER_PROFILE = System configuration issue,
    /// BETTING_SUSPENDED - Due to anomalous market circumstances bets are not currently being accepted on this line. Try again with next LineId.
    /// </value>
    [property: JsonPropertyName("errorCode")]
        SpecialBetResponse.SpecialBetResponseErrorCode? ErrorCode = null,
    /// <value>Bet identifier. Populated in case of accepted bet.</value>
    [property:
        JsonPropertyName("betId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? BetId = null,
    /// <value>Unique identifier provided in the request.</value>
    [property:
        JsonPropertyName("uniqueRequestId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? UniqueRequestId = null,
    /// <value>Win amount. Populated in case of accepted bet.</value>
    [property:
        JsonPropertyName("win"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Win = null,
    /// <value>Risk amount.  Populated in case of accepted bet.</value>
    [property:
        JsonPropertyName("risk"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Risk = null,
    /// <value>Bet price. Populated in case of accepted bet.</value>
    [property:
        JsonPropertyName("price"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Price = null,
    /// <value>Whether or not the bet was accepted on the line that changed in favour of client. This can be true only if acceptBetterLine in the Place Bet request is set to TRUE.</value>
    [property:
        JsonPropertyName("betterLineWasAccepted"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? BetterLineWasAccepted = null
)
{
    /// <summary>Status of the request.</summary>
    public record SpecialBetResponseStatus : ValueEnum<string>
    {
        internal SpecialBetResponseStatus(string value)
            : base(value) { }

        public SpecialBetResponseStatus()
            : base("ACCEPTED") { }

        public static SpecialBetResponseStatus Accepted = new("ACCEPTED");
        public static SpecialBetResponseStatus ProcessedWithError = new("PROCESSED_WITH_ERROR");
    }

    /// <summary>
    /// When Status is PROCESSED_WITH_ERROR, provides a code indicating the specific problem.
    ///
    /// ALL_BETTING_CLOSED = Betting is not allowed at this moment. This may happen during system maintenance.
    ///  ABOVE_MAX_BET_AMOUNT = Stake is above allowed maximum amount,
    ///  BELOW_MIN_BET_AMOUNT = Stake is below allowed minimum amount,
    ///  BLOCKED_BETTING = Betting is suspended for the client,
    ///  BLOCKED_CLIENT = Client is no longer active,
    ///  CONTEST_NOT_FOUND = Incorrect contest id provided or contest is no longer available,
    ///  DUPLICATED_REQUEST = UniqueRequestId must be unique for each bet,
    ///  INCOMPLETE_CUSTOMER_BETTING_PROFILE = Customer profile could not be loaded,
    ///  INSUFFICIENT_FUNDS = Bet is submitted by a client with insufficient funds,
    ///  INVALID_COUNTRY = Client country is not allowed for betting,
    ///  INVALID_REQUEST = Special bet request is not valid,
    ///  LINE_CHANGED = Bet is submitted on a line that has changed,
    ///  PAST_CUTOFFTIME = Bet is submitted on a game after the betting cutoff time,
    ///  RESPONSIBLE_BETTING_LOSS_LIMIT_EXCEEDED = Self-imposed loss limit exceeded,
    ///  RESPONSIBLE_BETTING_RISK_LIMIT_EXCEEDED = Self-imposed risk limit exceeded,
    ///  SYSTEM_ERROR_1 = Unexpected error,
    ///  SYSTEM_ERROR_2 = Unexpected error,
    ///  UNIQUE_REQUEST_ID_REQUIRED = UniqueRequestId is missing,
    ///  INVALID_CUSTOMER_PROFILE = System configuration issue,
    /// BETTING_SUSPENDED - Due to anomalous market circumstances bets are not currently being accepted on this line. Try again with next LineId.
    /// </summary>
    public record SpecialBetResponseErrorCode : ValueEnum<string>
    {
        internal SpecialBetResponseErrorCode(string value)
            : base(value) { }

        public SpecialBetResponseErrorCode()
            : base("ALL_BETTING_CLOSED") { }

        public static SpecialBetResponseErrorCode AllBettingClosed = new("ALL_BETTING_CLOSED");
        public static SpecialBetResponseErrorCode AboveMaxBetAmount = new("ABOVE_MAX_BET_AMOUNT");
        public static SpecialBetResponseErrorCode BelowMinBetAmount = new("BELOW_MIN_BET_AMOUNT");
        public static SpecialBetResponseErrorCode BlockedBetting = new("BLOCKED_BETTING");
        public static SpecialBetResponseErrorCode BlockedClient = new("BLOCKED_CLIENT");
        public static SpecialBetResponseErrorCode ContestNotFound = new("CONTEST_NOT_FOUND");
        public static SpecialBetResponseErrorCode DuplicatedRequest = new("DUPLICATED_REQUEST");
        public static SpecialBetResponseErrorCode IncompleteCustomerBettingProfile =
            new("INCOMPLETE_CUSTOMER_BETTING_PROFILE");
        public static SpecialBetResponseErrorCode InsufficientFunds = new("INSUFFICIENT_FUNDS");
        public static SpecialBetResponseErrorCode InvalidCountry = new("INVALID_COUNTRY");
        public static SpecialBetResponseErrorCode InvalidRequest = new("INVALID_REQUEST");
        public static SpecialBetResponseErrorCode LineChanged = new("LINE_CHANGED");
        public static SpecialBetResponseErrorCode PastCutofftime = new("PAST_CUTOFFTIME");
        public static SpecialBetResponseErrorCode ResponsibleBettingLossLimitExceeded =
            new("RESPONSIBLE_BETTING_LOSS_LIMIT_EXCEEDED");
        public static SpecialBetResponseErrorCode ResponsibleBettingRiskLimitExceeded =
            new("RESPONSIBLE_BETTING_RISK_LIMIT_EXCEEDED");
        public static SpecialBetResponseErrorCode SystemError1 = new("SYSTEM_ERROR_1");
        public static SpecialBetResponseErrorCode SystemError2 = new("SYSTEM_ERROR_2");
        public static SpecialBetResponseErrorCode UniqueRequestIdRequired =
            new("UNIQUE_REQUEST_ID_REQUIRED");
        public static SpecialBetResponseErrorCode InvalidCustomerProfile =
            new("INVALID_CUSTOMER_PROFILE");
        public static SpecialBetResponseErrorCode BettingSuspended = new("BETTING_SUSPENDED");
    }
}
