// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PinnacleBets.Json;

namespace PinnacleBets.Models;

public record TeaserBet(
    /// <value>Bet identification</value>
    [property: JsonPropertyName("betId")]
        long BetId,
    /// <value>Wager identification. All bets placed thru the API will have value 1. Website Classic view supports multiple contest(special) bets placement in the same bet slip in that case the bet would have appropriate wager number, as well as all round robin parlay bets.</value>
    [property: JsonPropertyName("wagerNumber")]
        long WagerNumber,
    /// <value>Date time when the bet was placed.</value>
    [property: JsonPropertyName("placedAt")]
        string PlacedAt,
    /// <value>
    /// Bet Status.
    ///
    /// ACCEPTED = Bet was accepted,
    /// CANCELLED = Bet is cancelled as per Pinnacle betting rules,
    /// LOSE = The bet is settled as lose,
    /// REFUNDED = When an event is cancelled or when the bet is settled as push, the bet will have REFUNDED status,
    /// WON = The bet is settled as won
    /// </value>
    [property: JsonPropertyName("betStatus")]
        TeaserBet.TeaserBetBetStatus BetStatus,
    [property: JsonPropertyName("betType")] string BetType,
    /// <value>Win amount.</value>
    [property: JsonPropertyName("win")]
        double Win,
    /// <value>Risk amount.</value>
    [property: JsonPropertyName("risk")]
        double Risk,
    /// <value>
    /// Bet odds format.
    /// AMERICAN = American odds format,
    /// DECIMAL = Decimal (European) odds format,
    /// HONGKONG = Hong Kong odds format,
    /// INDONESIAN = Indonesian odds format,
    /// MALAY = Malaysian odds format
    /// </value>
    [property: JsonPropertyName("oddsFormat")]
        OddsFormat OddsFormat,
    /// <value>Update Sequence</value>
    [property: JsonPropertyName("updateSequence")]
        long UpdateSequence,
    [property: JsonPropertyName("teaserName")] string TeaserName,
    [property: JsonPropertyName("isSameEventOnly")] bool IsSameEventOnly,
    [property: JsonPropertyName("minPicks")] double MinPicks,
    [property: JsonPropertyName("maxPicks")] double MaxPicks,
    [property: JsonPropertyName("legs")] List<TeaserLeg> Legs,
    /// <value>Unique Request Id</value>
    [property:
        JsonPropertyName("uniqueRequestId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? UniqueRequestId = null,
    /// <value>Win-Loss for settled bets.</value>
    [property:
        JsonPropertyName("winLoss"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? WinLoss = null,
    /// <value>Client’s commission on the bet.</value>
    [property:
        JsonPropertyName("customerCommission"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? CustomerCommission = null,
    /// <value>
    /// Possible keys \:
    /// * correctTeam1Id
    /// * correctTeam2Id
    /// * correctListedPitcher1
    /// * correctListedPitcher2
    /// * correctSpread
    /// * correctTotalPoints
    /// * correctTeam1TotalPoints
    /// * correctTeam2TotalPoints
    /// * correctTeam1Score
    /// * correctTeam2Score
    /// * correctTeam1TennisSetsScore
    /// * correctTeam2TennisSetsScore
    /// </value>
    [property:
        JsonPropertyName("cancellationReason"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        CancellationReason? CancellationReason = null,
    /// <value>Populated for all teaser bets and will be the original price at the time of the placement.</value>
    [property:
        JsonPropertyName("price"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Price = null,
    /// <value>Only for settled parlay. Final price may differ in case leg was cancelled or half won.</value>
    [property:
        JsonPropertyName("finalPrice"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? FinalPrice = null,
    /// <value>Reference to the teaser id</value>
    [property:
        JsonPropertyName("teaserId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? TeaserId = null,
    /// <value>Reference to the teaser group id</value>
    [property:
        JsonPropertyName("teaserGroupId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? TeaserGroupId = null
)
{
    /// <summary>
    /// Bet Status.
    ///
    /// ACCEPTED = Bet was accepted,
    /// CANCELLED = Bet is cancelled as per Pinnacle betting rules,
    /// LOSE = The bet is settled as lose,
    /// REFUNDED = When an event is cancelled or when the bet is settled as push, the bet will have REFUNDED status,
    /// WON = The bet is settled as won
    /// </summary>
    public record TeaserBetBetStatus : ValueEnum<string>
    {
        internal TeaserBetBetStatus(string value)
            : base(value) { }

        public TeaserBetBetStatus()
            : base("ACCEPTED") { }

        public static TeaserBetBetStatus Accepted = new("ACCEPTED");
        public static TeaserBetBetStatus Cancelled = new("CANCELLED");
        public static TeaserBetBetStatus Lose = new("LOSE");
        public static TeaserBetBetStatus Refunded = new("REFUNDED");
        public static TeaserBetBetStatus Won = new("WON");
    }
}
