// This file was generated by liblab | https://liblab.com/

using Environment = PinnacleBets.Http.Environment;

namespace PinnacleBets.Config;

/// <summary>
/// Configuration options for the PinnacleBetsClient.
/// </summary>
public record PinnacleBetsConfig(
    /// <value>The environment to use for the SDK.</value>
    Environment? Environment = null,
    /// <value>The basic authentication configuration.</value>
    BasicAuthConfig? BasicAuth = null
);
