// This file was generated by liblab | https://liblab.com/

namespace PinnacleBets.Http.Serialization;

public enum PathSerializationStyle
{
    Simple = SerializationStyle.Simple,
    Label = SerializationStyle.Label,
    Matrix = SerializationStyle.Matrix
}
